Extension/youtube react app
contentstack/extensions pull request #22
Opened 2021-05-20 07:17 UTC by Amitkanswal

2021-05-20 08:53 UTC, kego1992 commented on youtube/youtube-extension-popup/package.json
> +    "@testing-library/user-event": "^12.1.10",
Dev dependencies should ho in to devDependencies section

2021-07-27 11:31 UTC, ssurabhi10 commented on youtube/youtube-extension/src/Home.js
> +import ContentstackUIExtension from "@contentstack/ui-extensions-sdk";
Leave a line after all the import statements for more readability

2021-07-27 11:34 UTC, ssurabhi10 commented on youtube/youtube-extension/src/Home.js
> +export class Home extends React.Component {
Change Class components to Functional components because that is easy to use, more readable, have less line of code and comes in best practices

2021-07-27 12:56 UTC, ssurabhi10 requested changes

2021-07-27 13:02 UTC, ssurabhi10 commented on youtube/youtube-extension-popup/src/Popup.js
> +export class Popup extends React.Component {
Leave a line before starting the component (after `import` statements)

2021-07-27 13:38 UTC, ssurabhi10 requested changes

2021-07-27 13:38 UTC, ssurabhi10 commented on youtube/youtube-extension-popup/src/Popup.js
> +export class Popup extends React.Component {
- Leave a line before starting the component (after import statements)

- Change Class component to Functional component

2021-07-27 13:38 UTC, ssurabhi10 commented on youtube/youtube-extension-popup/src/Popup.js
> +  componentDidMount() {
Use Hooks instead of life cycle method

2021-07-27 13:38 UTC, ssurabhi10 commented on youtube/youtube-extension-popup/src/components/gridLayout.js
> +export default class GridLayout extends React.PureComponent {
Change Class Component to Functional Component

2021-07-27 13:38 UTC, ssurabhi10 commented on youtube/youtube-extension-popup/src/components/listLayout.js
> +export default class ListLayout extends React.PureComponent {
Use Functional Component

2021-07-27 13:38 UTC, ssurabhi10 commented on youtube/youtube-extension-popup/src/components/modal.js
> +export default class Modal extends React.PureComponent {
Use Functional Component

2021-07-27 13:38 UTC, ssurabhi10 commented on youtube/youtube-extension-popup/src/components/modal.js
> +  componentDidMount() {
Use Hooks instead of life cycle method

2021-07-27 13:38 UTC, ssurabhi10 commented on youtube/youtube-extension-popup/src/components/modal.js
> +  UNSAFE_componentWillReceiveProps(newProps) {
Use Hooks instead of life cycle method

2021-07-29 11:44 UTC, Amitkanswal commented
The above changes are along with some addon had already gone live. So I am closing this PR

2021-07-29 11:44 UTC, closed without merging